index:
    path: /
    controller: App\Controller\IndexController:getAllPupils

registration:
    path: /registration
    controller: App\Controller\RegistrationController:register

logout:
    path: /logout


#PASSWORD-------------------------------------------------------------------------------------------------

forgot_password:
    path: /forgotpassword
    controller: App\Controller\ForgotPasswordController:sendEmailWithChangePassword

change_password_if_you_forgot:
    path: /changepasswordifyouforgot/{user}
    controller: App\Controller\ChangePasswordIfYouForgotController:changePassword

change_password:
    path: /profile/changepassword
    controller: App\Controller\ChangePasswordController:changePassword



#EMAIL-------------------------------------------------------------------------------------------------

change_email:
    path: /profile/changemail
    controller: App\Controller\ChangeEmailController:changeEmail


#PROFILE-------------------------------------------------------------------------------------------------

change_avatar:
    path: /profile/changeavatar/{user}
    controller: App\Controller\ChangeAvatarController:changeAvatar

profile:
    path: /profile/{user}
    controller: App\Controller\ProfileUserController:viewUserProfile

#MODULE-------------------------------------------------------------------------------------------------

add_new_module:
    path: /addnewmodule
    controller: App\Controller\AddNewModuleController:addModule

view_module:
    path: /module/{module}
    controller: App\Controller\ViewModuleController:viewModule

observe_module:
    path: /observemodule/{module}/{user}
    controller: App\Controller\ObserveModuleController:observeModule

who_observe:
    path: /whobserve/{module}
    controller: App\Controller\ShowWhoObserveModulesController:showWhoObserveThisModule

remove_module:
    path: /removemodule/{module}
    controller: App\Controller\ViewModuleController:removeModule
#COMMENT-------------------------------------------------------------------------------------------------

edit_comment:
    path: /editcomment/{module}/{comment}
    controller: App\Controller\CommentController:editComment

remove_comment:
    path: /removecomment/{module}/{comment}
    controller: App\Controller\CommentController:removeComment