index:
    path: /
    controller: App\Controller\IndexController:getAllPupils

registration:
    path: /registration
    controller: App\Controller\RegistrationController:register

logout:
    path: /logout


#PASSWORD-------------------------------------------------------------------------------------------------

forgot_password:
    path: /forgotpassword
    controller: App\Controller\ForgotPasswordController:sendEmailWithChangePassword

change_password_if_you_forgot:
    path: /changepasswordifyouforgot/{user}
    controller: App\Controller\ChangePasswordIfYouForgotController:changePassword

change_password:
    path: /profile/changepassword
    controller: App\Controller\ChangePasswordController:changePassword



#EMAIL-------------------------------------------------------------------------------------------------

change_email:
    path: /profile/changemail
    controller: App\Controller\ChangeEmailController:changeEmail


#PROFILE-------------------------------------------------------------------------------------------------

change_avatar:
    path: /profile/changeavatar/{user}
    controller: App\Controller\ChangeAvatarController:changeAvatar

profile:
    path: /profile/{user}
    controller: App\Controller\ProfileUserController:viewUserProfile

#MODULE-------------------------------------------------------------------------------------------------

add_new_module:
    path: /addnewmodule
    controller: App\Controller\AddNewModuleController:addModule