index:
    path: /
    controller: App\Controller\IndexController:getAllPupils

registration:
    path: /registration
    controller: App\Controller\RegistrationController:register

forgot_password:
    path: /forgotpassword
    controller: App\Controller\ForgotPasswordController:sendEmailWithChangePassword
